import polars as pd

data = pd.read_csv("data/data.csv")

# Average of "Bottom Flywheel Measured Velocity" and "Top Flywheel Measured Velocity"
flywheel_vel = (data["Bottom Flywheel Measured Velocity"] + data["Top Flywheel Measured Velocity"]) / 2
# Total of "Bottom Flywheel Current" and "Top Flywheel Current"
flywheel_current = data["Bottom Flywheel Current"] + data["Top Flywheel Current"]

azimuth_vel = data["Azimuth Measured Velocity"]
azimuth_current = data["Azimuth Current"]

hood_vel = data["Hood Measured Velocity"]
hood_current = data["Hood Current"]

total_current = flywheel_current + azimuth_current + hood_current

# ---

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import numpy as np

X = pd.DataFrame({
    "flywheel_vel": flywheel_vel,
    "azimuth_vel": azimuth_vel,
    "hood_vel": hood_vel
})

def fit_model(current_set: pd.Series, degree=2) -> tuple[PolynomialFeatures, LinearRegression]:
    y = current_set
    poly = PolynomialFeatures(degree)
    X_poly = poly.fit_transform(X)

    model = LinearRegression()
    model.fit(X_poly, y)

    return (poly, model)

# ---

def create_equation(poly: PolynomialFeatures, model: LinearRegression) -> str:
    equation = "y = "

    for i, term in enumerate(poly.powers_):
        coeff = model.coef_[i] if i > 0 else model.intercept_
        if coeff == 0:
            continue
        term_str = " * ".join(
            f"{var}^{power}" if power > 1 else f"{var}" if power == 1 else ""
            for var, power in zip(X.columns, term)
        ).strip(" *").replace(" *  * ", " * ")
        if term_str == "":
            equation += f"{coeff:.8f}"
        else:
            equation += f"{coeff:.8f} * {term_str}"
        if i < len(poly.powers_) - 1:
            equation += " + "
    
    return equation

# ---

if __name__ == "__main__":
    import os

    flywheel_poly, flywheel_model = fit_model(flywheel_current)
    azimuth_poly, azimuth_model = fit_model(azimuth_current)
    hood_poly, hood_model = fit_model(hood_current)
    total_poly, total_model = fit_model(total_current)

    entries = [
        ("FlywheelCurrentModel", flywheel_poly, flywheel_model),
        ("AzimuthCurrentModel", azimuth_poly, azimuth_model),
        ("HoodCurrentModel", hood_poly, hood_model),
        ("TotalCurrentModel", total_poly, total_model)
    ]
    
    generated_file_path = os.path.join(os.path.dirname(__file__), "..", "..", "src/main/java/frc/robot/generated", "TurretTuningData.java")
    with open(generated_file_path, "w") as f:
        f.write(f"""package frc.robot.generated;

import org.wpilib.math.autodiff.Variable;

/**
 * Generated by `just tune_turret` - edits will be overwritten!  
 * Contains data tuned by `misc/turretTuning/analyze_data.py`.
 * Generated equations are as follows:
{
    "\n".join([f" * - {name}: {create_equation(poly, model)}" for (name, poly, model) in entries])
}
 */
public class TurretTuningData {{
""")

        for name, poly, model in entries:
            equation = create_equation(poly, model)
            f.write(f"    /**\n")
            f.write(f"     * All input velocities are in motor radians per second.\n")
            f.write(f"     * {equation}\n")
            f.write(f"     */\n")
            f.write(f"    public static final class {name} {{\n")
            
            def get_term(var: str, power: int) -> str:
                var_map = {
                    "flywheel_vel": "flywheel",
                    "azimuth_vel": "azimuth",
                    "hood_vel": "hood"
                }
                var = var_map.get(var, var)
                return f"{var}{power}" if power > 1 else f"{var}" if power == 1 else ""

            def get_term_var_name(i: int, coeff: float, powers: np.ndarray) -> tuple[float, str]:
                if i == 0:
                    return (model.intercept_, "bias")
                else:
                    return (coeff, "_".join(
                        get_term(var, power) for var, power in zip(X.columns, powers)
                    ).strip("_").replace("__", "_"))

            # All variables
            for i, (coeff, powers) in enumerate(zip(model.coef_, poly.powers_)):
                (coeff, term_str) = get_term_var_name(i, coeff, powers)
                f.write(f"        public static final double {term_str} = {coeff:.8f};\n")
                f.write(f"        private static final Variable {term_str}_var = new Variable({term_str});\n")
            
            # TODO: Remove terms which contribute very little

            # Calculation method
            f.write("\n")
            f.write(f"        public static double calculate(double flywheel, double azimuth, double hood) {{\n")
            f.write(f"            return ")
            for i, (coeff, powers) in enumerate(zip(model.coef_, poly.powers_)):
                if i == 0:
                    term_str = "bias"
                else:
                    (coeff, term_str) = get_term_var_name(i, coeff, powers)
                    for var, power in zip(X.columns, powers):
                        var_map = {
                            "flywheel_vel": "flywheel",
                            "azimuth_vel": "azimuth",
                            "hood_vel": "hood"
                        }
                        var_name = var_map.get(var, var)
                        if power > 1:
                            term_str += f" * Math.pow({var_name}, {power})"
                        elif power == 1:
                            term_str += f" * {var_name}"
                if i < len(model.coef_) - 1:
                    term_str += " + "
                f.write(term_str)
            f.write(";\n")
            f.write(f"        }}\n")

            # Calculation method for slepnir/autodiff
            f.write("\n")
            f.write(f"        public static Variable calculate(Variable flywheel, Variable azimuth, Variable hood) {{\n")
            f.write(f"            return ")
            # We need to turn this into something like
            # flywheel.times(0.1).times(azimuth).plus(hood.times(0.1))... etc etc
            for i, (coeff, powers) in enumerate(zip(model.coef_, poly.powers_)):
                if i == 0:
                    term_str = f"bias_var"
                else:
                    term_str = f"{get_term_var_name(i, coeff, powers)[1]}_var"
                    for var, power in zip(X.columns, powers):
                        var_map = {
                            "flywheel_vel": "flywheel",
                            "azimuth_vel": "azimuth",
                            "hood_vel": "hood"
                        }
                        var_name = var_map.get(var, var)
                        for _ in range(power):
                            term_str += f".times({var_name})"
                if i < len(model.coef_) - 1:
                    if i > 0:
                        term_str += ")"
                    term_str += ".plus("
                f.write(term_str)
            f.write(");\n")
            f.write(f"        }}\n")

            f.write(f"    }}\n")

        f.write("}\n")
    print("Results saved to code.")